yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'posts'

urlpatterns = [
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('', views.index, name='index')
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('group/slug:slug', include('posts.urls', namespace='group_posts')),
    path('profile/str:username', include('posts.urls', namespace='profile')),
    path('posts/int:post_id', include('posts.urls', namespace='post_detail')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='user')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='index')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название')
    slug = models.SlugField(unique=True, verbose_name='Уникальный ключ')
    description = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Содержимое')
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    text = models.TextField(verbose_name='Комментарий')
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации комментария'
    )


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_follow'
            ),
        ]


class Testing(models.Model):
    text = models.TextField(verbose_name='hello')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE(),
    )

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой относится пост',
        }
        labels = {
            'text': 'Текст поста',
            'group': 'Группа',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        help_texts = {
            'text': 'Текст комментария',
        }
        labels = {
            'text': 'Текст комментария',
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm, CommentForm
from .models import Group, Post, Follow


POSTS_ON_VIEW: int = 10


def paginator(request, posts):
    return Paginator(posts, POSTS_ON_VIEW).get_page(request.GET.get('page'))


def index(request):
    return render(request, 'posts/index.html', {
        'page_obj': paginator(
            request,
            Post.objects.select_related('group').all()
        ),
    })


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    return render(request, 'posts/group_list.html', {
        'group': group,
        'page_obj': paginator(request, group.posts.all()),
    })


def profile(request, username):
    author = get_object_or_404(User, username=username)
    following: bool = False
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user,
            author=get_object_or_404(User, username=username)
        ).exists()
    return render(request, 'posts/profile.html', {
        'page_obj': paginator(request, author.posts.all()),
        'author': author,
        'following': following
    })


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'posts/post_detail.html', {
        'post': post,
        'form': CommentForm(request.POST or None),
        'comments': post.comments.all()
    })


@login_required
def post_create(request):
    post_form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if post_form.is_valid():
        post = post_form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user)
    return render(request, 'posts/create_post.html', {'form': post_form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:index')
    post_form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if post_form.is_valid():
        post_form.save()
        return redirect('posts:post_detail', post_id)
    return render(request, 'posts/create_post.html', {
        'form': post_form,
        'post': post,
    })


@login_required
def add_comment(request, post_id):
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = get_object_or_404(Post, pk=post_id)
        comment.save()
    return redirect('posts:post_detail', post_id)


@login_required
def follow_index(request):
    following = Follow.objects.filter(
        user=request.user
    ).values_list('author', flat=True)
    return render(request, 'posts/follow.html', {
        'page_obj': paginator(
            request,
            Post.objects.filter(author__in=following)
        ),
    })


@login_required
def profile_follow(request, username):
    if request.user == get_object_or_404(User, username=username):
        return redirect('posts:profile', username)
    if Follow.objects.filter(
        user=request.user,
        author=get_object_or_404(User, username=username)
    ).exists():
        return redirect('posts:profile', username)
    Follow.objects.create(
        user=request.user,
        author=get_object_or_404(User, username=username)
    )
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    if request.user == get_object_or_404(User, username=username):
        return redirect('posts:profile', username)
    Follow.objects.filter(
        user=request.user,
        author=get_object_or_404(User, username=username)
    ).delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% load user_filters %}
{% block title %}
  {% if post %}Редактировать запись{% else %}Новая запись{% endif %}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if post %}Изменить пост{% else %}Новый пост{% endif %}
          </div>
          <div class="card-body">
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error }}
                </div>
              {% endfor %}
            {% endif %}
            <form method="post" enctype="multipart/form-data">{% csrf_token %}
              {% for field in form %}
                <div class="form-group row my-3 p-3">
                  <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  </label>
                  {{ field|addclass:"form-control" }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if post %}Сохранить{% else %}Добавить{% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% load thumbnail %}
{% load cache %}
{% block title %}
  Последние записи избранных авторов
{% endblock %}
{%block content%}
  {% cache 20 follow_page %}
    <div class="container py-5">
      {% include "posts/includes/switcher.html" %}
      {% for post in page_obj %}
        <ul>
          <li>
            Автор: <a href="{% url 'posts:profile' post.author.username %}">
              {{ post.author.username }}
            </a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          {% if post.group %}
            <li>
              Группа: 
              <a href="{% url 'posts:group_posts' post.group.slug %}">
                {{ post.group.title }}
              </a>
            </li>
          {% endif %}
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p class="text-right">{{ post.text|linebreaks }}</p>
        <button type="button" class="btn btn-light">
          <a
          href = "{% url 'posts:post_detail' post.pk %}"
          class="btn btn-info pull-right"
          >
            Просмотреть запись
          </a>
        </button>
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    {% include 'posts/includes/paginator.html' %}
    </div>
  {% endcache %}
{%endblock%}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1> {{ group.title }} </h1>
    <p> {{ group.description|linebreaks }}</p>
    {% for post in page_obj %}
      <ul>
        <li>
          Автор: 
          <a href="{% url 'posts:profile' post.author.username %}">
            {{ post.author.username }}
          </a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text|linebreaks }}</p>
      <button type="button" class="btn btn-light">
        <a
          href = "{% url 'posts:post_detail' post.pk %}"
          class="btn btn-info pull-right"
        >
          Просмотреть запись
        </a>
      </button>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{%endblock%}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% load thumbnail %}
{% load cache %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{%block content%}
  {% cache 20 index_page %}
    <div class="container py-5">
      {% include "posts/includes/switcher.html" %}
      {% for post in page_obj %}
        <ul>
          <li>
            Автор: <a href="{% url 'posts:profile' post.author.username %}">
              {{ post.author.username }}
            </a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          {% if post.group %}
            <li>
              Группа: 
              <a href="{% url 'posts:group_posts' post.group.slug %}">
                {{ post.group.title }}
              </a>
            </li>
          {% endif %}
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p class="text-right">{{ post.text|linebreaks }}</p>
        <button type="button" class="btn btn-light">
          <a
          href = "{% url 'posts:post_detail' post.pk %}"
          class="btn btn-info pull-right"
          >
            Просмотреть запись
          </a>
        </button>
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    {% include 'posts/includes/paginator.html' %}
    </div>
  {% endcache %}
{%endblock%}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load user_filters %}
{% load thumbnail %}
{% block title %}
  Пост {{ post.text|truncatechars:30 }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Автор: <a href="{% url 'posts:profile' post.author.username %}">
            {{ post.author.username }}
        </a>
      </li>

      <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>

      {% if post.group %}
        <li class="list-group-item">
          Группа: 
          <a href="{% url 'posts:group_posts' post.group.slug %}">
            {{ post.group.title }}
          </a>
        </li>
      {% endif %}
      <li class="list-group-item">
        Всего постов автора: {{ post.author.posts.count }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text|linebreaks }}</p>
    {% if user == post.author %}
      <a href="{% url 'posts:post_edit' post.pk %}">
        <button  type="submit" class="btn btn-primary">
          Редактировать
        </button>
      </a>
    {% endif %}
      {% if user.is_authenticated %}
      <div class="card my-4">
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
          <form method="POST" action="{% url 'posts:add_comment' post.pk %}">
            {% csrf_token %}      
            <div class="form-group mb-2">
              {{ form.text|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
          </form>
        </div>
      </div>
    {% endif %}

    {% for comment in comments %}
      <div class="media mb-4">
        <div class="media-body">
          <h5 class="mt-0">
            <a href="{% url 'posts:profile' comment.author.username %}">
              {{ comment.author.username }}
            </a>
          </h5>
            <p>
            {{ comment.text }}
            </p>
          </div>
        </div>
    {% endfor %}
  </div>
{%endblock%}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
  Профайл пользователя {{ author.username }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ author.posts.count }}</h3>
    <div class="mb-3">
      {% if author != request.user %}
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
        {% endif %}
      {% endif %}
    </div>
    <div>
      {% for post in page_obj %}
        <ul>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          {% if post.group %}
            <li>
              Группа: 
              <a href="{% url 'posts:group_posts' post.group.slug %}">
                {{ post.group.title }} 
                <!--По моему скромному мнению, это выглядит куда лучше,
                чем отдальная строчка с кнопкой 'все посты группы'-->
              </a>
            </li>
          {% endif %}
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text|linebreaks }}</p>
        <button type="button" class="btn btn-light">
          <a
            href = "{% url 'posts:post_detail' post.pk %}"
            class="btn btn-info pull-right"
          >
            Просмотреть запись
          </a>
        </button>
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </div>
  </div>
{% endblock %}